language: node_js
node_js:
- '9'
script:
- npm run lint
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  app: ml-dietrich
  api_key:
    secure: c4fd2a1wgz0GHoFoaEX7c2j0Onf7bBFotECTnC4fWJXTX1PztHx97yi8XtfDr9LtN7HZSRETemhtgBZdGyRjYQffgvGK7eQyim+58MqBfr6GQlteQI2X6MkTUYP19p8C5F+IuTW5DbZlBmAJbnwVoi1pjq0Kq+Kn2cFy3pz6aCeaQEAdXDXeKQZPfgoRJGrNxl/Q9yF8bK33cLl7eFqpWmll2HqUOLFMPPfYyfan6ak9v0PtBO5E2DpQDimRyyz27fZ/DFKI/Yq4QHSO13NmhfCToutrrmNR/W23gujyL6Q+tCU9uS5N4w+F3LOoKda90/bv8And9EOR2OeXuUNkERQ6Bd1f2YfgqyC5X1kJUl4OUaMbciaGkWYyJo/hgAzyvAHp2TtupVJoYVe+jptQrEyCSNZVNbxGNIQ54IJD2A25AjTN4Of9R2NGzEz/WUFO3EDTc4GCSAamb4eOx6UaSchgCgqg3Knr3lEOaka/1ky785CrtNfkZzRRMy2V66OgvwaM8krpn5nsd6OctAR7e05WzNoOIayM1NP1Tnds5pjS5ytQpllXI2gAyiBS9xgZ/VdjgqKzQR+669pU+/gr1b0ogNsQzSCBt+zndkcEqL4nLgONTwoLh9AkvA5sqL4dRsd1rOTsdYTsx5j1Lf240oVtD9JJWnayIGUjZACl688=
