language: node_js
node_js:
- '9'
script:
- npm run lint
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  app: ml-dietrich
  api_key:
    secure: ml8pnOPY8Hu9uml5M9+Px3YwZ3HEIhwwKixmG9GvIhe9TrQXgIGltiXICPg4P/Qg7IT5XU84szw8YbbnIL6OyrteOh2zclc2YyaDz8fWDWbSTMxI3PK10v1wMCLUBxlB5iHwoENc7C+PunzGkrYW9oqoLGxWqlfzKSTb3PhG0zDHk/gvt+eDnMKhPyssFeOkY68kN03IjZGp3v+DYLa6iolp+n7CbfYbVi/Crccu0kFpf02BqOxJsyzoU0R9BtiwIO+BIK2/v8XSGxA8EnL7lURF7Nc9VZG4ksq1WH19Hzyu8UBCgCRlrDT63eQbw6VzZjF57eKl/g3j8J5geVcxIrHN0Bd3ZhPsqxLXfia7usUaEKyC7zVzqBalGFhmIsRavSlblA3dn/be/tOWRqfFjSAoUuy5e+ukC+UJ83KgeSgFjBLdYt31DcF0Het8HTtD/OLCr/2mo/SPYNSf90AizkGDR/hFP3MHby1wRS52lT8+cPDH+5VDS2OG5HuuPDEVU6cZPU8TyfHpHNS0kvCcdbDoNXoytVTGnwlr5+NiSU/RfOqVb82H8nPxoBwDwCmy9ZY8WNApTnZRz7RaKxqcSX6J4JLqL68p+UHs/zrh18dU6iNhWiP6/6DBwF251xzY3GeWhGZtak0/jQK1JcnbD4z3FR99SORXz5YRH/JUYiU=
